//! 中文说明：本文件位于 candidate-pipeline/lib.rs，用于说明该模块的核心实现。
pub mod candidate_pipeline;
pub mod filter;
pub mod hydrator;
pub mod query_hydrator;
pub mod scorer;
pub mod selector;
pub mod side_effect;
pub mod source;
pub mod util;
